/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kresika;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class jHomePage extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jHomePage.class.getName());

    /**
     * Creates new form jHomePage
     */
    public jHomePage() {
        initComponents();
        jName.setText("Guest");
        setLocationRelativeTo(null);
    }

    public jHomePage(String fullname) {
        initComponents();

    
        
        
        // Label Tulisan Welcome, User
        jName.setText(fullname);

        setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAddSchedule = new javax.swing.JButton();
        jBtnBook = new javax.swing.JButton();
        jPaymentHistory = new javax.swing.JButton();
        jName = new javax.swing.JLabel();
        jBtnLogout = new javax.swing.JButton();
        jBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home Page");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1728, 1117));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jAddSchedule.setContentAreaFilled(false);
        jAddSchedule.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jAddSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddScheduleActionPerformed(evt);
            }
        });
        getContentPane().add(jAddSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 700, 550, 80));

        jBtnBook.setContentAreaFilled(false);
        jBtnBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBookActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, 550, 80));

        jPaymentHistory.setContentAreaFilled(false);
        jPaymentHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPaymentHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPaymentHistoryActionPerformed(evt);
            }
        });
        getContentPane().add(jPaymentHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 580, 550, 80));

        jName.setFont(new java.awt.Font("Baloo Da 2", 1, 36)); // NOI18N
        jName.setText("Jname");
        getContentPane().add(jName, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 356, 350, 40));

        jBtnLogout.setContentAreaFilled(false);
        jBtnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1435, 33, 280, 80));

        jBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/HomePageB.png"))); // NOI18N
        getContentPane().add(jBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBookActionPerformed
        new jAvailabelDate().setVisible(true); // Pindah ke halaman utama
        this.dispose();
    }//GEN-LAST:event_jBtnBookActionPerformed

    private void jAddScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddScheduleActionPerformed
        new jAddSchedule().setVisible(true); // Pindah ke halaman utama
        this.dispose();
    }//GEN-LAST:event_jAddScheduleActionPerformed

    private void jPaymentHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPaymentHistoryActionPerformed
        new jPaymentHistory().setVisible(true); // Pindah ke halaman utama
        this.dispose();
    }//GEN-LAST:event_jPaymentHistoryActionPerformed

    private void jBtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLogoutActionPerformed
        int response = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to logout?",
                "Logout Confirmation",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        // Jika pengguna menekan tombol "Yes"
        if (response == JOptionPane.YES_OPTION) {
            // Kembali ke halaman login
            new loginPage().setVisible(true);
            // Tutup halaman saat ini
            this.dispose();
        }
    }//GEN-LAST:event_jBtnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jHomePage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddSchedule;
    private javax.swing.JLabel jBackground;
    private javax.swing.JButton jBtnBook;
    private javax.swing.JButton jBtnLogout;
    private javax.swing.JLabel jName;
    private javax.swing.JButton jPaymentHistory;
    // End of variables declaration//GEN-END:variables
}
