/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kresika;

/**
 *
 * @author Administrator
 */



public class jHomePage extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jHomePage.class.getName());

    /**
     * Creates new form jHomePage
     */
    public jHomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPaymentHistory = new javax.swing.JButton();
        jBtnBook = new javax.swing.JButton();
        jBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home Page");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1728, 1117));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPaymentHistory.setContentAreaFilled(false);
        jPaymentHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPaymentHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPaymentHistoryActionPerformed(evt);
            }
        });
        getContentPane().add(jPaymentHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 590, 550, 80));

        jBtnBook.setContentAreaFilled(false);
        jBtnBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBookActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 463, 550, 80));

        jBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/HomePage.png"))); // NOI18N
        getContentPane().add(jBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBookActionPerformed
        new jAvailabelDate().setVisible(true); // Pindah ke halaman utama
        this.dispose();
    }//GEN-LAST:event_jBtnBookActionPerformed

    private void jPaymentHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPaymentHistoryActionPerformed
        new jPaymentHistory().setVisible(true); // Pindah ke halaman utama
        this.dispose();
    }//GEN-LAST:event_jPaymentHistoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jHomePage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBackground;
    private javax.swing.JButton jBtnBook;
    private javax.swing.JButton jPaymentHistory;
    // End of variables declaration//GEN-END:variables
}
