/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kresika;

import javax.swing.JOptionPane;

/**
 *
 * @author Hbiiiiii2
 */
public class jPassangerForm extends javax.swing.JFrame {

    // Variabel untuk menyimpan data yang diterima dari halaman sebelumnya
    private String namaKeretaDiterima;
    private String ruteLengkapDiterima;
    private String kodeKelasDiterima;
    private String waktuBerangkatDiterima;
    private double hargaSatuanDiterima;
    private String trainCodeDiterima;

    /**
     * Creates new form jPassangerForm
     */
    public jPassangerForm() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Passenger Details (Test Mode)");

        if (jRoute != null) {
            jRoute.setText("Route Not Selected");
        }
        if (jDate != null) {
            jDate.setText("Date Not Selected");
        }
        if (jSeatClass != null) {
            jSeatClass.setText("Seat Class Not Selected");
        }
    }

    public jPassangerForm(String namaKereta, String ruteLengkap, String kodeKelas, String waktuBerangkat, double hargaSatuan, String trainCode) {
        initComponents(); // Inisialisasi semua komponen GUI terlebih dahulu

        // Simpan data yang diterima ke variabel instance
        this.namaKeretaDiterima = namaKereta;
        this.ruteLengkapDiterima = ruteLengkap;
        this.kodeKelasDiterima = kodeKelas;
        this.waktuBerangkatDiterima = waktuBerangkat;
        this.hargaSatuanDiterima = hargaSatuan;
        this.trainCodeDiterima = trainCode;

        // --- MENGGUNAKAN DATA YANG DITERIMA ---
        // Mengatur nilai yang diterima ke komponen GUI yang sesuai
        if (jRoute != null) {
            jRoute.setText(this.ruteLengkapDiterima);
        }

        if (jDate != null) {
            // Ekstrak hanya bagian tanggal (YYYY-MM-DD) dari timestamp
//            String tanggalSaja = this.waktuBerangkatDiterima.split(" ")[0];
            jDate.setText(this.waktuBerangkatDiterima);
        }
        
        if (jSeatClass != null) {
            jSeatClass.setText(namaKeretaDiterima + " - " + kodeKelas);
        }

        
        // Atur properti window
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Passenger Data Form");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jName = new javax.swing.JTextField();
        jEmail = new javax.swing.JTextField();
        jRoute = new javax.swing.JTextField();
        jSeatClass = new javax.swing.JTextField();
        jSpinnerNumberofTicket = new javax.swing.JSpinner();
        jButtonBack = new javax.swing.JButton();
        jButtonCO = new javax.swing.JButton();
        jDate = new javax.swing.JTextField();
        jBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jName.setFont(new java.awt.Font("Baloo Da 2", 0, 24)); // NOI18N
        jName.setBorder(null);
        jName.setOpaque(true);
        getContentPane().add(jName, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 357, 830, 40));

        jEmail.setFont(new java.awt.Font("Baloo Da 2", 0, 24)); // NOI18N
        jEmail.setBorder(null);
        jEmail.setOpaque(true);
        getContentPane().add(jEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 463, 830, 40));

        jRoute.setEditable(false);
        jRoute.setBackground(new java.awt.Color(255, 255, 255));
        jRoute.setFont(new java.awt.Font("Baloo Da 2", 0, 24)); // NOI18N
        jRoute.setForeground(new java.awt.Color(255, 51, 51));
        jRoute.setBorder(null);
        jRoute.setOpaque(true);
        jRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRouteActionPerformed(evt);
            }
        });
        getContentPane().add(jRoute, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 578, 320, 40));

        jSeatClass.setEditable(false);
        jSeatClass.setBackground(new java.awt.Color(255, 255, 255));
        jSeatClass.setFont(new java.awt.Font("Baloo Da 2", 0, 24)); // NOI18N
        jSeatClass.setForeground(new java.awt.Color(255, 51, 51));
        jSeatClass.setBorder(null);
        jSeatClass.setOpaque(true);
        jSeatClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSeatClassActionPerformed(evt);
            }
        });
        getContentPane().add(jSeatClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 690, 410, 40));

        jSpinnerNumberofTicket.setFont(new java.awt.Font("Baloo Da 2", 0, 24)); // NOI18N
        jSpinnerNumberofTicket.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinnerNumberofTicket.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jSpinnerNumberofTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 690, 320, 40));

        jButtonBack.setContentAreaFilled(false);
        jButtonBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 950, 320, 80));

        jButtonCO.setContentAreaFilled(false);
        jButtonCO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCOActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCO, new org.netbeans.lib.awtextra.AbsoluteConstraints(1285, 953, 320, 80));

        jDate.setEditable(false);
        jDate.setBackground(new java.awt.Color(255, 255, 255));
        jDate.setFont(new java.awt.Font("Baloo Da 2", 0, 24)); // NOI18N
        jDate.setForeground(new java.awt.Color(255, 51, 51));
        jDate.setBorder(null);
        jDate.setOpaque(true);
        jDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDateActionPerformed(evt);
            }
        });
        getContentPane().add(jDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 578, 410, 40));

        jBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Passenger FormC.png"))); // NOI18N
        getContentPane().add(jBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        System.out.println("Back button is clicked.");
        // Logika untuk kembali
        new jAvailabelDate().setVisible(true); // Membuka home
        this.dispose(); // Menutup form ini
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCOActionPerformed
        System.out.println("The Checkout button is clicked.");

        // 1. Ambil data dari field
        String nama = jName.getText().trim();
        String email = jEmail.getText().trim();
        int jumlahTiket = (Integer) jSpinnerNumberofTicket.getValue(); // Mengambil nilai dari JSpinner

        // 2. Validasi Input
        if (nama.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Name and Email are required!", "Incomplete Input", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!email.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
            JOptionPane.showMessageDialog(this, "Invalid email format!", "Incorrect Input", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (jumlahTiket <= 0) {
            JOptionPane.showMessageDialog(this, "The number of tickets must be more than 0!", "Incorrect Input", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 3. Proses data (misalnya, tampilkan ringkasan sebelum simpan ke DB)
        double totalHarga = jumlahTiket * this.hargaSatuanDiterima;

        jPayment paymentForm = new jPayment(
                nama,
                email,
                jumlahTiket,
                totalHarga,
                this.namaKeretaDiterima,
                this.ruteLengkapDiterima,
                this.waktuBerangkatDiterima,
                this.kodeKelasDiterima,
                this.trainCodeDiterima
        );

        paymentForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCOActionPerformed

    private void jRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRouteActionPerformed
        new jAvailabelDate().show(true);
    }//GEN-LAST:event_jRouteActionPerformed

    private void jDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateActionPerformed

    private void jSeatClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSeatClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSeatClassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jPassangerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jPassangerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jPassangerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jPassangerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jPassangerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jPassangerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jPassangerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jPassangerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Panggil konstruktor default saat menjalankan file ini secara langsung
                new jPassangerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBackground;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonCO;
    private javax.swing.JTextField jDate;
    private javax.swing.JTextField jEmail;
    private javax.swing.JTextField jName;
    private javax.swing.JTextField jRoute;
    private javax.swing.JTextField jSeatClass;
    private javax.swing.JSpinner jSpinnerNumberofTicket;
    // End of variables declaration//GEN-END:variables
}
