/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kresika;

import javax.swing.JOptionPane;

/**
 *
 * @author hbi2z
 */
public class jPassangerForm extends javax.swing.JFrame {

    private String ruteDiterima;
    private String kelasKeretaDiterima;

    /**
     * Creates new form jPassangerForm
     */
    public jPassangerForm(String rutePilihan, String kelasPilihan) {
        this.ruteDiterima = rutePilihan;
        this.kelasKeretaDiterima = kelasPilihan;
        // if (tanggalPilihan != null) { this.tanggalDiterima = tanggalPilihan; }

        initComponents(); // Sangat penting untuk memanggil ini pertama di konstruktor

        // Mengatur nilai default atau yang diterima ke komponen GUI
        if (jRoute != null) { // Periksa apakah jRoute sudah diinisialisasi oleh initComponents()
            jRoute.setText(this.ruteDiterima); //
            // jRoute.setEditable(false); // Anda sudah mengatur ini di initComponents()
        }
        
//        if (jSeatNumber != null){
//            jSeatNumber.setText(rutePilihan);
//        }


        // if (jDate != null && this.tanggalDiterima != null) {
        //    jDate.setText(this.tanggalDiterima);
        //    // jDate.setEditable(false); // Anda sudah mengatur ini di initComponents()
        // }

        // Menambahkan ActionListener untuk tombol yang belum diatur oleh GUI Builder (jika ada)
        // jButtonCheckout sudah memiliki listener dari initComponents()
        System.out.println("Form Penumpang Dibuka untuk Rute: " + this.ruteDiterima + ", Kelas: " + this.kelasKeretaDiterima); //
        // Ubah default close operation agar tidak menutup seluruh aplikasi
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detail Penumpang"); // Judul window yang lebih sesuai

    }

    public jPassangerForm() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detail Penumpang (Mode Tes)");
        System.out.println("Form Penumpang dibuka tanpa data rute/kelas (dari konstruktor default).");
        // Anda mungkin ingin menonaktifkan beberapa field atau menampilkan pesan
        if (jRoute != null) {
            jRoute.setText("Rute Belum Dipilih");
        }
        if (jDate != null) {
            jDate.setText("Tanggal Belum Dipilih");
        }
        // Tambahkan listener juga di sini jika diperlukan (misalnya untuk tombol back)
        if (jButtonBack != null) {
            for (java.awt.event.ActionListener al : jButtonBack.getActionListeners()) {
                jButtonBack.removeActionListener(al);
            }
            jButtonBack.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonBackActionPerformed(evt);
                }
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeatNumber = new javax.swing.JTextField();
        jName = new javax.swing.JTextField();
        jEmail = new javax.swing.JTextField();
        jNumberTicket = new javax.swing.JTextField();
        jRoute = new javax.swing.JTextField();
        jDate = new javax.swing.JTextField();
        jButtonBack = new javax.swing.JButton();
        jButtonCO = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeatNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jSeatNumber.setForeground(new java.awt.Color(255, 51, 51));
        jSeatNumber.setBorder(null);
        jSeatNumber.setOpaque(true);
        getContentPane().add(jSeatNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 692, 320, 40));

        jName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jName.setBorder(null);
        jName.setOpaque(true);
        getContentPane().add(jName, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 357, 830, 40));

        jEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jEmail.setBorder(null);
        jEmail.setOpaque(true);
        getContentPane().add(jEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 463, 830, 40));

        jNumberTicket.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jNumberTicket.setBorder(null);
        jNumberTicket.setOpaque(true);
        getContentPane().add(jNumberTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 691, 410, 40));

        jRoute.setEditable(false);
        jRoute.setBackground(new java.awt.Color(255, 255, 255));
        jRoute.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRoute.setForeground(new java.awt.Color(255, 51, 51));
        jRoute.setBorder(null);
        jRoute.setOpaque(true);
        jRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRouteActionPerformed(evt);
            }
        });
        getContentPane().add(jRoute, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 578, 320, 40));

        jDate.setEditable(false);
        jDate.setBackground(new java.awt.Color(255, 255, 255));
        jDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jDate.setForeground(new java.awt.Color(255, 51, 51));
        jDate.setBorder(null);
        jDate.setOpaque(true);
        getContentPane().add(jDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 578, 410, 40));

        jButtonBack.setContentAreaFilled(false);
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 950, 320, 80));

        jButtonCO.setContentAreaFilled(false);
        jButtonCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCOActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCO, new org.netbeans.lib.awtextra.AbsoluteConstraints(1285, 953, 320, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/PassengerForm.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        System.out.println("Tombol Back diklik.");
        // Logika untuk kembali ke jHomePage atau menutup form ini
        new jHomePage().setVisible(true); // Jika ingin membuka instance baru jHomePage
        this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCOActionPerformed
        System.out.println("Tombol Checkout diklik.");

        // 1. Ambil data dari field
        String nama = jName.getText().trim();
        String email = jEmail.getText().trim();
        // String tanggal = jDate.getText().trim(); // jDate tidak bisa diedit, nilainya dari ruteDiterima atau tanggalDiterima
        String nomorKursi = jSeatNumber.getText().trim(); // jSeatNumber mungkin perlu dibuat editable atau diisi otomatis
        String jumlahTiketStr = jNumberTicket.getText().trim();

        // Data yang sudah ada:
        // this.ruteDiterima
        // this.kelasKeretaDiterima
        // this.tanggalDiterima (jika Anda menambahkannya)
        // 2. Validasi
        if (nama.isEmpty() || email.isEmpty() || jumlahTiketStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama, Email, dan Jumlah Tiket wajib diisi!", "Input Tidak Lengkap", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!email.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
            JOptionPane.showMessageDialog(this, "Format email tidak valid!", "Input Salah", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int jumlahTiket;
        try {
            jumlahTiket = Integer.parseInt(jumlahTiketStr);
            if (jumlahTiket <= 0) {
                JOptionPane.showMessageDialog(this, "Jumlah tiket harus lebih dari 0!", "Input Salah", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Jumlah tiket harus berupa angka!", "Input Salah", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // (Tambahkan validasi lain jika perlu: nomor kursi, dll.)
        // 3. Proses data (misalnya, simpan ke database atau tampilkan ringkasan)
        System.out.println("Data Pemesanan:");
        System.out.println("Nama: " + nama);
        System.out.println("Email: " + email);
        System.out.println("Rute: " + this.ruteDiterima);
        System.out.println("Kelas: " + this.kelasKeretaDiterima);
        System.out.println("Tanggal: " + jDate.getText()); // Ambil dari field jDate yang sudah di-set
        System.out.println("Nomor Kursi: " + (nomorKursi.isEmpty() ? "Belum dipilih/otomatis" : nomorKursi));
        System.out.println("Jumlah Tiket: " + jumlahTiket);

        JOptionPane.showMessageDialog(this, "Data pemesanan (lihat konsol). Lanjutkan ke proses berikutnya.", "Checkout Berhasil (Simulasi)", JOptionPane.INFORMATION_MESSAGE);

        // Contoh: pindah ke form konfirmasi
        // jConfirmationForm confirmForm = new jConfirmationForm(dataPemesanan);
        // confirmForm.setVisible(true);
        // this.dispose();
    }//GEN-LAST:event_jButtonCOActionPerformed

    private void jRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRouteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRouteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jPassangerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jPassangerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jPassangerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jPassangerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jPassangerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jPassangerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jPassangerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jPassangerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Panggil konstruktor default saat menjalankan file ini secara langsung
                new jPassangerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonCO;
    private javax.swing.JTextField jDate;
    private javax.swing.JTextField jEmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jName;
    private javax.swing.JTextField jNumberTicket;
    private javax.swing.JTextField jRoute;
    private javax.swing.JTextField jSeatNumber;
    // End of variables declaration//GEN-END:variables
}
