/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kresika;

import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Administrator
 */
public class jPayment extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jPayment.class.getName());
    private double totalHargaDiterima;

    /**
     * Creates new form jPayment
     */
    public jPayment() {
        initComponents();
        setTitle("Rincian Pembayaran (No Data)");
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jChangeDue.setText("Rp 0"); // Inisialisasi awal
    }

    public jPayment(String nama, String email, int jumlahTiket, double totalHarga, String namaKereta, String rute, String waktuBerangkat, String kelas) {
        initComponents(); // Inisialisasi komponen UI

        // Simpan total harga untuk perhitungan kembalian
        this.totalHargaDiterima = totalHarga;

        // --- TAMPILKAN DATA YANG DITERIMA DI UI ---
        // Membuat formatter untuk mata uang Indonesia
        NumberFormat formatter = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));

        // Mengisi semua JLabel dengan data yang diterima
        jName.setText(nama);
        jEmail.setText(email);
        jNumberTicket.setText(String.valueOf(jumlahTiket));
        jSeatClass.setText(kelas);
        jTujuan1.setText(rute); // Menggunakan jTujuan1 untuk menampilkan rute
        jTotalPayment.setText(formatter.format(this.totalHargaDiterima));
        jChangeDue.setText("Rp 0"); // Inisialisasi awal

        // --- LOGIKA KEMBALIAN OTOMATIS ---
        addCashReceivedListener();

        // Atur properti window
        setTitle("Rincian Pembayaran");
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null); // Menengahkan window
    }

    private void addCashReceivedListener() {
        jChashReceived.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                calculateChange();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                calculateChange();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                calculateChange();
            }
        });
    }

    private void calculateChange() {
        String cashText = jChashReceived.getText();
        if (cashText.isEmpty()) {
            jChangeDue.setText("Rp 0");
            return;
        }

        try {
            double cashReceived = Double.parseDouble(cashText);
            double changeDue = cashReceived - this.totalHargaDiterima;

            // Format kembalian ke format mata uang
            NumberFormat formatter = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));
            jChangeDue.setText(formatter.format(changeDue));

        } catch (NumberFormatException ex) {
            // Jika input bukan angka, kembalian dianggap 0 atau tampilkan pesan error
            jChangeDue.setText("Input tidak valid");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTotalPayment = new javax.swing.JLabel();
        jName = new javax.swing.JLabel();
        jNumberTicket = new javax.swing.JLabel();
        jEmail = new javax.swing.JLabel();
        jSeatClass = new javax.swing.JLabel();
        jChangeDue = new javax.swing.JLabel();
        jChashReceived = new javax.swing.JTextField();
        jTujuan1 = new javax.swing.JLabel();
        jBack = new javax.swing.JButton();
        jPayBtn = new javax.swing.JButton();
        jBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTotalPayment.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTotalPayment.setText("jLabel2");
        jTotalPayment.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jTotalPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 500, 240, 30));

        jName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jName.setText("jLabel2");
        jName.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jName, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 330, 30));

        jNumberTicket.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jNumberTicket.setText("jLabel2");
        jNumberTicket.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jNumberTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 300, 330, 30));

        jEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jEmail.setText("jLabel2");
        jEmail.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 330, 30));

        jSeatClass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jSeatClass.setText("jLabel2");
        jSeatClass.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jSeatClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 350, 330, 30));

        jChangeDue.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jChangeDue.setText("jLabel2");
        jChangeDue.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jChangeDue, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 750, 500, 70));
        getContentPane().add(jChashReceived, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 752, 320, 90));

        jTujuan1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTujuan1.setText("jLabel2");
        jTujuan1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jTujuan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 500, 240, 30));

        jBack.setContentAreaFilled(false);
        jBack.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 930, 330, 100));

        jPayBtn.setContentAreaFilled(false);
        jPayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPayBtnActionPerformed(evt);
            }
        });
        getContentPane().add(jPayBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 933, 350, 100));

        jBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/PaymentB.png"))); // NOI18N
        getContentPane().add(jBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPayBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPayBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jPayment().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBack;
    private javax.swing.JLabel jBackground;
    private javax.swing.JLabel jChangeDue;
    private javax.swing.JTextField jChashReceived;
    private javax.swing.JLabel jEmail;
    private javax.swing.JLabel jName;
    private javax.swing.JLabel jNumberTicket;
    private javax.swing.JButton jPayBtn;
    private javax.swing.JLabel jSeatClass;
    private javax.swing.JLabel jTotalPayment;
    private javax.swing.JLabel jTujuan1;
    // End of variables declaration//GEN-END:variables
}
